//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ ���ɵİ����ļ���
// �� OCCMFC.rc ʹ��
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_OCCMFCTYPE                  130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDD_ROBOT_CONTROL_PANEL         164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_PAGE_ROBOT                  314
#define IDD_PAGE_WELD                   316
#define IDC_EDIT_J1                     1000
#define IDC_SLIDER_J1                   1001
#define IDC_EDIT_J2                     1012
#define IDC_SLIDER_J2                   1013
#define IDC_EDIT_J3                     1014
#define IDC_SLIDER_J3                   1015
#define IDC_EDIT_J4                     1024
#define IDC_SLIDER_J4                   1025
#define IDC_EDIT_J5                     1026
#define IDC_SLIDER_J5                   1027
#define IDC_EDIT_J6                     1028
#define IDC_SLIDER_J6                   1029
#define IDC_EDIT_PX                     1030
#define IDC_EDIT_PY                     1031
#define IDC_EDIT_PZ                     1032
#define IDC_EDIT_PW                     1036
#define IDC_EDIT_PP                     1037
#define IDC_EDIT_PX6                    1038
#define IDC_EDIT_PR                     1038
#define IDC_BUTTON_IMPORT_MODEL         1039
#define IDC_EDIT_IMPORT_X               1040
#define IDC_EDIT_IMPORT_Y               1041
#define IDC_EDIT_IMPORT_Z               1042
#define IDC_BUTTON_DELETE_SELECTED      1043
#define IDC_COMBO1                      1044
#define IDC_BUTTON_PAGE_ROBOT           1045
#define IDC_HOTKEY1                     1045
#define IDC_BUTTON_PAGE_WELD            1046
#define IDC_BUTTON_IDENTIFY_WELD        1047
#define IDC_TAB_WELD                    1048
#define IDC_LIST_WELD                   1049
#define IDC_STATIC_WELD_TITLE          1050
#define ID_32771                        32771
#define ID_BUTTON_CLEAR_ALL             32772
#define ID_32773                        32773
#define ID_FANUC_M10ID12                32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_32778                        32778
#define ID_32779                        32779
#define ID_ABB_ABB1410                  32780
#define ID_EFORT_ER20D                  32781
#define ID_GSK_GSKRB08                  32782
#define ID_GSK_GSKRB20                  32783
#define ID_KAWASAKI_BA006N              32784
#define ID_STEP_STEPSA1400              32785
#define ID_STEP_STEPSA1800              32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1051
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
